# Site
name: 'Singapore Malayalees'
description: 'News, Events and More...'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'https://sgmalayalees.github.io/'
baseurl: ''
disqus: 'singaporemalayalees-com'
email: 'team.singaporemalayalees@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
google-adsense: 'ca-pub-1676785078101005'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    traveldesk:
      name:           traveldesk
      site:           https://singaporemalayalees.com
      avatar:         /assets/images/avatar-traveldesk.png
      bio:            "We are traveldesk"
      email:          team.singaporemalayalees@gmail.com
      twitter:        https://twitter.com/SG_Malayalees

    sgmalayalees:
      name:           NewsDesk
      site:           https://singaporemalayalees.com
      avatar:         /assets/images/avatar-sgmalayalees.jpg
      bio:            "News, Events and More...!"
      email:          team.singaporemalayalees@gmail.com
      twitter:        https://twitter.com/SG_Malayalees
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]